// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package bungeecord

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "bungeecord", asset.ModuleFieldsPri, AssetBungeecord); err != nil {
		panic(err)
	}
}

// AssetBungeecord returns asset data.
// This is the base64 encoded zlib format compressed contents of module/bungeecord.
func AssetBungeecord() string {
	return "eJyclb1u4zAMgPc8BdG93W7xcEMDHFCgbW4o0LFQYkYRIokGRfnitz/4B3biKHFsjzL5faREQc9wxCqDbfQacUecrwDEiMUMnobFpxVAjmHHphBDPoPfKwA4y4IPyqPFFcDeoM1D1vx/Bq8cjuj1J1WBGWimWHQrCfol65xnSfdrKdhNYPutyYsyPnR82DM5kAPCa1Pnuu7Hkg4vZ1njUoZixDi8wF+Y30lfR7QVH7H6N2zJBfLAqPIJ6HUMnpQr6pP7RJEKvomPyPC2ga/r2LYEwZMk/BZLtPf1dUha/vb5ZzOr28JGbfx9XSKmF75Hr9YHJY/35zAEpSdOLRXUO78OJkBALpHBBODovfEavpUg75W1UCIHQx60kaxffX4lkiCsiqwjwbYCl//8mqp9qFzY7MKtOX9ksjvEy+QNWjryH61g/tiTt8bjz46il9v4TRMF11Et3nhBjZycM1UhT+H/NlEtPkCB3B1zQjXesNSWDXrGQJF3l1tyV077PilVxO2OBymehNUsY5OxVBcOVMyy1QmLeytxdJCTvdUZi3uLXJpS2Xn9dUlLpTmWs3w5lktVlrbbapasyZin6++i8frOHRz/XXLf3Oi9GDmc8cZFd13JI3vl1OkuW52Ws1WJPH53Rvwu5DY/p7i1uPofAAD//54wtSo="
}
